alsanchez_bakdigest_create_backup:
  path: /backup
  defaults: { _controller: AlSanchezBakDigestBundle:CreateBackup:index }
  methods: [POST]

alsanchez_bakdigest_create_backup_notification:
  path: /backup/{backupId}/notification
  defaults: { _controller: AlSanchezBakDigestBundle:CreateBackupNotification:index }
  methods: [POST]

alsanchez_bakdigest_create_digest:
  path: /digest
  defaults: { _controller: AlSanchezBakDigestBundle:CreateDigest:index }
  methods: [POST]