alsanchez_bakdigest_create_backup:
  path: /backup
  defaults: { _controller: AlSanchezBakDigestBundle:CreateBackup:index }
  methods: [POST]

alsanchez_bakdigest_delete_backup:
  path: /backup/{backupId}
  defaults: { _controller: AlSanchezBakDigestBundle:DeleteBackup:index }
  methods: [DELETE]

alsanchez_bakdigest_list_backups:
  path: /backup
  defaults: { _controller: AlSanchezBakDigestBundle:ListBackups:index }
  methods: [GET]

alsanchez_bakdigest_create_backup_notification:
  path: /backup/{backupId}/notification
  defaults: { _controller: AlSanchezBakDigestBundle:CreateBackupNotification:index }
  methods: [POST]

alsanchez_bakdigest_create_digest:
  path: /digest
  defaults: { _controller: AlSanchezBakDigestBundle:CreateDigest:index }
  methods: [POST]
  
alsanchez_bakdigest_delete_digest:
  path: /digest/{digestId}
  defaults: { _controller: AlSanchezBakDigestBundle:DeleteDigest:index }
  methods: [DELETE]

alsanchez_bakdigest_update_digest_delivery:
  path: /digest/{digestId}/delivery
  defaults: { _controller: AlSanchezBakDigestBundle:UpdateDigestDelivery:index }
  methods: [PUT]