parameters:
#    al_sanchez_bak_digest.example.class: AlSanchez\BakDigestBundle\Example

services:
#    al_sanchez_bak_digest.example:
#        class: %al_sanchez_bak_digest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
