AlSanchez\BakDigestBundle\Entity\Digest:
    type: entity
    table: digest
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        periodicity:
            type: integer
        email:
            type: string
        last_delivery:
            type: datetime
    manyToMany:
        backups:
            targetEntity: AlSanchez\BakDigestBundle\Entity\Backup
            joinTable:
                name: digest_backup
                joinColumns:
                    digest_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    backup_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"